In [1]:
import pandas as pd
import numpy as np

In [44]:
data = pd.read_csv("raw/INFY.csv")

In [45]:
data

,Date,Open,High,Low,Close,Adj Close,Volume
0,1996-01-01,1.589840,1.593360,1.582030,1.593360,-0.007420,102400.0
1,1996-01-02,1.589840,1.597660,1.586910,1.586910,-0.007390,102400.0
2,1996-01-03,1.597660,1.597660,1.597660,1.597660,-0.007440,51200.0
3,1996-01-04,1.582030,1.589840,1.582030,1.587110,-0.007391,153600.0
4,1996-01-05,1.568360,1.568360,1.568360,1.568360,-0.007304,25600.0
5,1996-01-08,1.568360,1.582030,1.570310,1.578130,-0.007349,179200.0
6,1996-01-09,1.578130,1.562500,1.542970,1.560550,-0.007267,435200.0
7,1996-01-10,1.560550,1.550780,1.542970,1.546880,-0.007204,179200.0
8,1996-01-11,1.558590,1.582030,1.546880,1.582030,-0.007367,409600.0
9,1996-01-12,1.574220,1.574220,1.562500,1.573240,-0.007326,179200.0
10,1996-01-15,1.552730,1.570310,1.552730,1.555660,-0.007245,153600.0
11,1996-01-16,1.555660,1.562500,1.425780,1.562500,-0.007276,179200.0
12,1996-01-17,1.562500,1.566410,1.542970,1.547660,-0.007207,384000.0
13,1996-01-18,1.547660,1.552730,1.539060,1.552730,-0.007231,102400.0
14,1996-01-19,1.542970,1.542970,1.536130,1.537110,-0.007158,256000.0
15,1996-01-22,1.542970,1.552730,1.542970,1.552730,-0.007231,102400.0
16,1996-01-23,1.535160,1.562500,1.535160,1.547850,-0.007208,332800.0
17,1996-01-24,1.547850,1.541020,1.505860,1.541020,-0.007176,204800.0
18,1996-01-25,1.541990,1.541990,1.535160,1.535160,-0.007149,51200.0
19,1996-01-26,NaN,NaN,NaN,NaN,NaN,NaN
20,1996-01-29,1.531250,1.531250,1.526370,1.526370,-0.007108,51200.0
21,1996-01-30,1.526370,1.550780,1.542970,1.544920,-0.007195,716800.0
22,1996-01-31,1.544920,1.562500,1.535160,1.562500,-0.007276,230400.0
23,1996-02-01,1.562500,1.621090,1.562500,1.621090,-0.007549,409600.0
24,1996-02-02,1.621090,1.679690,1.621090,1.679490,-0.007821,1177600.0
25,1996-02-05,1.679490,1.683590,1.640820,1.679690,-0.007822,409600.0
26,1996-02-06,1.679690,1.767580,1.679690,1.718750,-0.008004,691200.0
27,1996-02-07,1.718750,1.687500,1.667970,1.673050,-0.007791,486400.0
28,1996-02-08,1.699220,1.777340,1.699220,1.777340,-0.008277,384000.0
29,1996-02-09,1.777340,1.855470,1.660160,1.845120,-0.008593,691200.0
...,...,...,...,...,...,...,...
5618,2018-03-21,1170.000000,1175.500000,1162.199951,1167.500000,1167.500000,3846497.0
5619,2018-03-22,1164.500000,1177.449951,1155.300049,1161.300049,1161.300049,3406584.0
5620,2018-03-23,1147.000000,1173.800049,1142.349976,1167.599976,1167.599976,6004042.0
5621,2018-03-26,1166.900024,1166.900024,1144.000000,1155.250000,1155.250000,4465361.0
5622,2018-03-27,1160.000000,1161.300049,1150.099976,1154.000000,1154.000000,1901044.0
5623,2018-03-28,1150.750000,1150.750000,1126.250000,1131.800049,1131.800049,6279161.0
5624,2018-04-02,1141.000000,1149.550049,1121.300049,1137.150024,1137.150024,4036351.0
5625,2018-04-03,1134.699951,1143.550049,1128.099976,1140.449951,1140.449951,2038584.0
5626,2018-04-04,1144.000000,1144.550049,1120.000000,1124.199951,1124.199951,2406651.0
5627,2018-04-05,1139.550049,1151.300049,1129.099976,1147.550049,1147.550049,3881772.0
5628,2018-04-06,1143.000000,1146.000000,1122.099976,1127.000000,1127.000000,2968871.0
5629,2018-04-09,1125.000000,1125.800049,1106.550049,1111.250000,1111.250000,3601441.0
5630,2018-04-10,1112.000000,1124.500000,1105.400024,1113.400024,1113.400024,4463029.0
5631,2018-04-11,1118.000000,1131.500000,1116.500000,1124.250000,1124.250000,4512787.0
5632,2018-04-12,1129.449951,1172.750000,1125.000000,1162.599976,1162.599976,8522183.0
5633,2018-04-13,1174.000000,1185.900024,1150.250000,1171.449951,1171.449951,10613519.0
5634,2018-04-16,1102.000000,1140.000000,1102.000000,1133.199951,1133.199951,12372542.0
5635,2018-04-17,1127.000000,1127.400024,1115.000000,1125.199951,1125.199951,5198970.0
5636,2018-04-18,1122.849976,1134.750000,1113.849976,1125.949951,1125.949951,5215190.0
5637,2018-04-19,1124.000000,1139.800049,1123.099976,1132.849976,1132.849976,4262771.0
5638,2018-04-20,1139.000000,1193.699951,1136.949951,1178.449951,1178.449951,12136346.0
5639,2018-04-23,1168.000000,1214.400024,1155.250000,1187.699951,1187.699951,10915319.0
5640,2018-04-24,1185.000000,1196.400024,1150.099976,1154.500000,1154.500000,4263108.0
5641,2018-04-25,1152.000000,1171.000000,1145.199951,1160.349976,1160.349976,5797089.0
5642,2018-04-26,1174.000000,1181.650024,1160.000000,1176.449951,1176.449951,5651042.0
5643,2018-04-27,1180.000000,1191.599976,1174.199951,1185.199951,1185.199951,3831685.0
5644,2018-04-30,1181.699951,1207.949951,1180.650024,1199.500000,1199.500000,2755839.0
5645,2018-05-02,1198.900024,1201.599976,1181.000000,1197.050049,1197.050049,5147521.0
5646,2018-05-03,1197.250000,1204.699951,1176.099976,1182.550049,1182.550049,2666115.0
5647,2018-05-04,1185.000000,1186.000000,1155.000000,1173.099976,1173.099976,3011684.0

In [46]:
temp = list(data["Close"].copy())
temp = [0] + temp[:-1]
len(temp)
data["prev_close"] = temp

In [47]:
data["change"] = data["Close"] - data["prev_close"]
data["percentage_change"] = data["change"] * 100 / data["Close"]

In [48]:
np.mean(data["percentage_change"])

0.090040284844180862

In [49]:
data

,Date,Open,High,Low,Close,Adj Close,Volume,prev_close,change,percentage_change
0,1996-01-01,1.589840,1.593360,1.582030,1.593360,-0.007420,102400.0,0.000000,1.593360,100.000000
1,1996-01-02,1.589840,1.597660,1.586910,1.586910,-0.007390,102400.0,1.593360,-0.006450,-0.406450
2,1996-01-03,1.597660,1.597660,1.597660,1.597660,-0.007440,51200.0,1.586910,0.010750,0.672859
3,1996-01-04,1.582030,1.589840,1.582030,1.587110,-0.007391,153600.0,1.597660,-0.010550,-0.664730
4,1996-01-05,1.568360,1.568360,1.568360,1.568360,-0.007304,25600.0,1.587110,-0.018750,-1.195516
5,1996-01-08,1.568360,1.582030,1.570310,1.578130,-0.007349,179200.0,1.568360,0.009770,0.619087
6,1996-01-09,1.578130,1.562500,1.542970,1.560550,-0.007267,435200.0,1.578130,-0.017580,-1.126526
7,1996-01-10,1.560550,1.550780,1.542970,1.546880,-0.007204,179200.0,1.560550,-0.013670,-0.883714
8,1996-01-11,1.558590,1.582030,1.546880,1.582030,-0.007367,409600.0,1.546880,0.035150,2.221829
9,1996-01-12,1.574220,1.574220,1.562500,1.573240,-0.007326,179200.0,1.582030,-0.008790,-0.558720
10,1996-01-15,1.552730,1.570310,1.552730,1.555660,-0.007245,153600.0,1.573240,-0.017580,-1.130067
11,1996-01-16,1.555660,1.562500,1.425780,1.562500,-0.007276,179200.0,1.555660,0.006840,0.437760
12,1996-01-17,1.562500,1.566410,1.542970,1.547660,-0.007207,384000.0,1.562500,-0.014840,-0.958867
13,1996-01-18,1.547660,1.552730,1.539060,1.552730,-0.007231,102400.0,1.547660,0.005070,0.326522
14,1996-01-19,1.542970,1.542970,1.536130,1.537110,-0.007158,256000.0,1.552730,-0.015620,-1.016193
15,1996-01-22,1.542970,1.552730,1.542970,1.552730,-0.007231,102400.0,1.537110,0.015620,1.005970
16,1996-01-23,1.535160,1.562500,1.535160,1.547850,-0.007208,332800.0,1.552730,-0.004880,-0.315276
17,1996-01-24,1.547850,1.541020,1.505860,1.541020,-0.007176,204800.0,1.547850,-0.006830,-0.443213
18,1996-01-25,1.541990,1.541990,1.535160,1.535160,-0.007149,51200.0,1.541020,-0.005860,-0.381719
19,1996-01-26,NaN,NaN,NaN,NaN,NaN,NaN,1.535160,NaN,NaN
20,1996-01-29,1.531250,1.531250,1.526370,1.526370,-0.007108,51200.0,NaN,NaN,NaN
21,1996-01-30,1.526370,1.550780,1.542970,1.544920,-0.007195,716800.0,1.526370,0.018550,1.200709
22,1996-01-31,1.544920,1.562500,1.535160,1.562500,-0.007276,230400.0,1.544920,0.017580,1.125120
23,1996-02-01,1.562500,1.621090,1.562500,1.621090,-0.007549,409600.0,1.562500,0.058590,3.614235
24,1996-02-02,1.621090,1.679690,1.621090,1.679490,-0.007821,1177600.0,1.621090,0.058400,3.477246
25,1996-02-05,1.679490,1.683590,1.640820,1.679690,-0.007822,409600.0,1.679490,0.000200,0.011907
26,1996-02-06,1.679690,1.767580,1.679690,1.718750,-0.008004,691200.0,1.679690,0.039060,2.272582
27,1996-02-07,1.718750,1.687500,1.667970,1.673050,-0.007791,486400.0,1.718750,-0.045700,-2.731538
28,1996-02-08,1.699220,1.777340,1.699220,1.777340,-0.008277,384000.0,1.673050,0.104290,5.867757
29,1996-02-09,1.777340,1.855470,1.660160,1.845120,-0.008593,691200.0,1.777340,0.067780,3.673474
...,...,...,...,...,...,...,...,...,...,...
5618,2018-03-21,1170.000000,1175.500000,1162.199951,1167.500000,1167.500000,3846497.0,1164.550049,2.949951,0.252672
5619,2018-03-22,1164.500000,1177.449951,1155.300049,1161.300049,1161.300049,3406584.0,1167.500000,-6.199951,-0.533880
5620,2018-03-23,1147.000000,1173.800049,1142.349976,1167.599976,1167.599976,6004042.0,1161.300049,6.299927,0.539562
5621,2018-03-26,1166.900024,1166.900024,1144.000000,1155.250000,1155.250000,4465361.0,1167.599976,-12.349976,-1.069031
5622,2018-03-27,1160.000000,1161.300049,1150.099976,1154.000000,1154.000000,1901044.0,1155.250000,-1.250000,-0.108319
5623,2018-03-28,1150.750000,1150.750000,1126.250000,1131.800049,1131.800049,6279161.0,1154.000000,-22.199951,-1.961473
5624,2018-04-02,1141.000000,1149.550049,1121.300049,1137.150024,1137.150024,4036351.0,1131.800049,5.349975,0.470472
5625,2018-04-03,1134.699951,1143.550049,1128.099976,1140.449951,1140.449951,2038584.0,1137.150024,3.299927,0.289353
5626,2018-04-04,1144.000000,1144.550049,1120.000000,1124.199951,1124.199951,2406651.0,1140.449951,-16.250000,-1.445472
5627,2018-04-05,1139.550049,1151.300049,1129.099976,1147.550049,1147.550049,3881772.0,1124.199951,23.350098,2.034778
5628,2018-04-06,1143.000000,1146.000000,1122.099976,1127.000000,1127.000000,2968871.0,1147.550049,-20.550049,-1.823429
5629,2018-04-09,1125.000000,1125.800049,1106.550049,1111.250000,1111.250000,3601441.0,1127.000000,-15.750000,-1.417323
5630,2018-04-10,1112.000000,1124.500000,1105.400024,1113.400024,1113.400024,4463029.0,1111.250000,2.150024,0.193104
5631,2018-04-11,1118.000000,1131.500000,1116.500000,1124.250000,1124.250000,4512787.0,1113.400024,10.849976,0.965086
5632,2018-04-12,1129.449951,1172.750000,1125.000000,1162.599976,1162.599976,8522183.0,1124.250000,38.349976,3.298639
5633,2018-04-13,1174.000000,1185.900024,1150.250000,1171.449951,1171.449951,10613519.0,1162.599976,8.849975,0.755472
5634,2018-04-16,1102.000000,1140.000000,1102.000000,1133.199951,1133.199951,12372542.0,1171.449951,-38.250000,-3.375397
5635,2018-04-17,1127.000000,1127.400024,1115.000000,1125.199951,1125.199951,5198970.0,1133.199951,-8.000000,-0.710985
5636,2018-04-18,1122.849976,1134.750000,1113.849976,1125.949951,1125.949951,5215190.0,1125.199951,0.750000,0.066610
5637,2018-04-19,1124.000000,1139.800049,1123.099976,1132.849976,1132.849976,4262771.0,1125.949951,6.900025,0.609086
5638,2018-04-20,1139.000000,1193.699951,1136.949951,1178.449951,1178.449951,12136346.0,1132.849976,45.599975,3.869488
5639,2018-04-23,1168.000000,1214.400024,1155.250000,1187.699951,1187.699951,10915319.0,1178.449951,9.250000,0.778816
5640,2018-04-24,1185.000000,1196.400024,1150.099976,1154.500000,1154.500000,4263108.0,1187.699951,-33.199951,-2.875700
5641,2018-04-25,1152.000000,1171.000000,1145.199951,1160.349976,1160.349976,5797089.0,1154.500000,5.849976,0.504156
5642,2018-04-26,1174.000000,1181.650024,1160.000000,1176.449951,1176.449951,5651042.0,1160.349976,16.099975,1.368522
5643,2018-04-27,1180.000000,1191.599976,1174.199951,1185.199951,1185.199951,3831685.0,1176.449951,8.750000,0.738272
5644,2018-04-30,1181.699951,1207.949951,1180.650024,1199.500000,1199.500000,2755839.0,1185.199951,14.300049,1.192167
5645,2018-05-02,1198.900024,1201.599976,1181.000000,1197.050049,1197.050049,5147521.0,1199.500000,-2.449951,-0.204666
5646,2018-05-03,1197.250000,1204.699951,1176.099976,1182.550049,1182.550049,2666115.0,1197.050049,-14.500000,-1.226164
5647,2018-05-04,1185.000000,1186.000000,1155.000000,1173.099976,1173.099976,3011684.0,1182.550049,-9.450073,-0.805564

In [50]:
data = data.drop(data.index[0])

In [52]:
data[data["percentage_change"] > 10.0]

,Date,Open,High,Low,Close,Adj Close,Volume,prev_close,change,percentage_change
305,1997-03-03,4.527340,4.588670,4.375000,4.588480,0.113727,947200.0,4.007810,0.580670,12.654953
825,1999-03-01,48.046902,48.842999,46.640598,48.842999,8.635937,4277056.0,41.875000,6.967999,14.266116
1152,2000-05-31,208.718994,219.343994,208.718994,218.710999,44.641102,10948096.0,195.841995,22.869004,10.456266
1201,2000-08-08,202.811996,233.408005,202.811996,233.102005,47.578453,37985760.0,201.212006,31.889999,13.680706
1357,2001-03-14,134.688004,149.968994,132.190994,147.548004,30.463165,13967680.0,131.005005,16.542999,11.211944
1382,2001-04-18,96.468803,110.766998,95.593803,110.766998,22.869255,21695904.0,95.489098,15.277900,13.792827
1390,2001-04-30,102.500000,117.459000,101.938004,115.905998,25.602470,17568480.0,101.514000,14.391998,12.416957
1963,2003-07-10,109.375000,115.438004,109.375000,113.337997,41.992760,65399200.0,101.605003,11.732994,10.352216
3427,2009-05-18,426.250000,477.725006,420.250000,450.024994,282.026215,69812.0,398.200012,51.824982,11.516023
4338,2013-01-11,630.250000,680.500000,630.250000,678.025024,520.982117,46426284.0,580.575012,97.450012,14.372628
4960,2015-07-21,1035.000000,1149.000000,1035.000000,1112.650024,1047.355835,19155056.0,1001.250000,111.400024,10.012135